### PR TITLE
Trying to build a docker image in CircleCI

### PR DESCRIPTION
**Pull request by jasonbarry**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
🎉 dev - Your [FeaturePeek environment](https://dashboard.dev.featurepeek.com/peek/5m3h1v) is ready for your team to preview!

**Review by ghost — COMMENTED** [review]
🎉 dev - Your [FeaturePeek environment](https://dashboard.dev.featurepeek.com/peek/5m3h1v) is ready for your team to preview!

**Review by ghost — COMMENTED** [review]
🎉 dev - Your [FeaturePeek environment](https://dashboard.dev.featurepeek.com/peek/5m3h1v) is ready for your team to preview!

**Review by ghost — COMMENTED** [review]
🎉 dev - Your [FeaturePeek environment](https://dashboard.dev.featurepeek.com/peek/5m3h1v) is ready for your team to preview!

**Review by ghost — COMMENTED** [review]
🎉 dev - Your [FeaturePeek environment](https://dashboard.dev.featurepeek.com/peek/5m3h1v) is ready for your team to preview!

**Review by jasonbarry — COMMENTED** [review]
screenshot  Can you see the above screenshot?  <detail><summary>Browser metadata</summary>*More markdown will appear here*</detail>

**Review by jasonbarry — COMMENTED** [review]
screenshot  cool  
<details><summary>Browser metadata</summary>

    Page URL:      /show/135/hasty-treat-cranky-developers
    Browser:       Safari 12.0.3 / Mac OS 10.14.3
    Viewport:      1280 x 714
    Screen DPI:    2x
    Language:      en-US
    Cookies:       Yes

</details>

🔗 [View on FeaturePeek](http://localhost:3000/peek/5m3h1v#/show/135/hasty-treat-cranky-developers)

**Review by jasonbarry — COMMENTED** [review]
screenshot  
the element selection action should be asynchronous   
<details><summary>Browser metadata</summary>

    Page path:     /show/135/hasty-treat-cranky-developers
    Browser:       Safari 12.0.3 / Mac OS 10.14.3
    Viewport:      1280 x 714
    Screen DPI:    2x
    Language:      en-US
    Cookies:       Yes

</details>

🔗 [View on FeaturePeek](http://localhost:3000/peek/5m3h1v#/show/135/hasty-treat-cranky-developers)

**Review by jasonbarry — COMMENTED** [review]
screenshot  background opacity should be additive  
<details><summary>Browser metadata</summary>

    Page path:     /show/135/hasty-treat-cranky-developers
    Browser:       Safari 12.0.3 / Mac OS 10.14.3
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

🔗 [View on FeaturePeek](http://localhost:3000/peek/5m3h1v#/show/135/hasty-treat-cranky-developers)

**Review by jasonbarry — COMMENTED** [review]
screenshot  also the image screenshot should have *width* and *height* attributes if possible  
<details><summary>Browser metadata</summary>

    Page path:     /show/135/hasty-treat-cranky-developers
    Browser:       Safari 12.0.3 / Mac OS 10.14.3
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

🔗 [View on FeaturePeek](http://localhost:3000/peek/5m3h1v#/show/135/hasty-treat-cranky-developers)

**Review by jasonbarry — COMMENTED** [review]
screenshot  looking good  
<details><summary>Browser metadata</summary>

    Page path:     /show/135/hasty-treat-cranky-developers
    Browser:       Safari 12.0.3 / Mac OS 10.14.3
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

🔗 [View on FeaturePeek](http://localhost:3000/peek/5m3h1v#/show/135/hasty-treat-cranky-developers)

**Review by jasonbarry — COMMENTED** [review]
screenshot  hoyabembe  
<details><summary>Browser metadata</summary>

    Page path:     /show/135/hasty-treat-cranky-developers
    Browser:       Safari 12.0.3 / Mac OS 10.14.3
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

🔗 [View on FeaturePeek](http://localhost:3000/peek/5m3h1v#/show/135/hasty-treat-cranky-developers)

**Review by jasonbarry — COMMENTED** [review]
screenshot  background included?  
<details><summary>Browser metadata</summary>

    Page path:     /show/135/hasty-treat-cranky-developers
    Browser:       Safari 12.0.3 / Mac OS 10.14.3
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

🔗 [View on FeaturePeek](http://localhost:3000/peek/5m3h1v#/show/135/hasty-treat-cranky-developers)

**Pull request merged**
